### ISSUE TITLE
Shows old card info directly after write

### ISSUE THREAD

**Issue by jmbott** [SEL-Columbia/minigrid-server#56]
Pretty sure this is an issue with the server and not the Operator Module. 

Shows no card when no card is there, (good)
![image](https://user-images.githubusercontent.com/7769317/27677565-3006e244-5c80-11e7-88da-7278354ace06.png)

Shows current card when card is placed, (good)
![image](https://user-images.githubusercontent.com/7769317/27677614-4fee00c4-5c80-11e7-8887-8aaac4b0ea33.png)

Press write card button (good)
![image](https://user-images.githubusercontent.com/7769317/27677623-5abdf61c-5c80-11e7-9175-56539b0c255f.png)

Read value on site goes blank (good)
![image](https://user-images.githubusercontent.com/7769317/27677695-92f264fa-5c80-11e7-9517-2823e9fd38cc.png)

Read value on site reverts to last (to change)
![image](https://user-images.githubusercontent.com/7769317/27677614-4fee00c4-5c80-11e7-8887-8aaac4b0ea33.png)

Operator box sends new value
New Value is displayed. (good)
![image](https://user-images.githubusercontent.com/7769317/27677660-732a6cb2-5c80-11e7-8d66-31bde882281a.png)

**Comment by vr2262** [comment]
How about at this step:

Read value on site goes blank (good)

You get a spinner or some kind of message like "checking new card information..."?

**Comment by jmbott** [comment]
Yea that could work. As long as it continues through this stage, 

Read value on site reverts to last (to change)
